[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/requests"
  to = "/.netlify/functions/requests"
  status = 200

[[redirects]]
  from = "/api/requests/:id/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/api/feedback"
  to = "/.netlify/functions/feedback"
  status = 200

[[redirects]]
  from = "/api/requests/:id"
  to = "/.netlify/functions/delete-request"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"